project:
  type: website

website:
  title: "Global CO2 Emissions"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: Sources.qmd
        text: Sources
      - href: about.qmd
        text: About

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true



